repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path=.app/pyproject.toml]
        additional_dependencies: [toml]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --recursive
          - --expand-star-imports
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-unused-variables

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--config=.app/pyproject.toml]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--settings-path=.app/pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [--config-file=.app/pyproject.toml]
        additional_dependencies: [pydantic, sqlalchemy-stubs==0.4]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
