version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: app_db
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306" # port重複防止のため、local側は3306以外とする
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - db_volume:/var/lib/mysql
      #- ./docker/dump_sql/seed.sql.gz:/docker-entrypoint-initdb.d/install_docker.sql.gz
  
  # web:
  #   container_name: backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8090:80
  #   volumes:
  #     - ./manaus:/manaus
  #   links:
  #     - db
  #   restart: always
  #   networks:
  #     - network
  #   tty: true


volumes:
  db_volume:
    driver: local

networks:
  network:
    driver: bridge


